-- ============================================================
-- SMG GUIDE - schedules テーブル & RPC関数
-- ------------------------------------------------------------
-- Supabase ダッシュボードの SQL Editor に貼り付けて実行してください。
-- 既存の posts テーブル・既存の関数・既存の記事データには
-- 一切変更を加えません（新しいテーブルと新しい関数を追加するだけです）。
--
-- ⚠️ 実行前に必ず、このファイル内の
--     'REPLACE_WITH_YOUR_PASSPHRASE'
--    を、実際に使っている「合言葉」に置き換えてください。
--    posts の管理画面と同じ合言葉にすれば、管理者は
--    同じ合言葉で記事投稿とスケジュール管理の両方を操作できます。
-- ============================================================

-- 1. テーブル本体
create table if not exists public.schedules (
  id                     bigint generated by default as identity primary key,

  -- 基本情報
  title                  text not null,
  title_en               text,
  title_kr               text,
  title_tr               text,
  title_de               text,

  rule_label             text,
  tag_color              text not null default 'pink'
                           check (tag_color in ('orange','purple','pink','red','green')),

  image_url              text,

  -- 日時（ST = サーバー時間 基準）
  recurrence_type        text not null default 'weekly'
                           check (recurrence_type in ('weekly','once')),
  day_of_week            smallint check (day_of_week between 0 and 6), -- 0=日,1=月,...6=土
  specific_date          date,
  st_time                time not null,

  -- メモ
  note_text              text,
  note_text_en           text,
  note_text_kr           text,
  note_text_tr           text,
  note_text_de           text,

  important_text         text,
  important_text_en      text,
  important_text_kr      text,
  important_text_tr      text,
  important_text_de      text,

  -- 既存記事への任意リンク（postsをそのまま参照。postsには影響なし）
  link_post_id            bigint references public.posts(id) on delete set null,

  sort_order               integer not null default 0,
  published                 boolean not null default true,

  created_at                timestamptz not null default now(),
  updated_at                 timestamptz,

  constraint schedules_recurrence_fields_chk check (
    (recurrence_type = 'weekly' and day_of_week is not null and specific_date is null)
    or
    (recurrence_type = 'once' and specific_date is not null and day_of_week is null)
  )
);

create index if not exists schedules_published_idx on public.schedules (published);
create index if not exists schedules_recurrence_idx on public.schedules (recurrence_type, day_of_week, specific_date);

-- 2. RLS（Row Level Security）
alter table public.schedules enable row level security;

-- 公開済みのスケジュールは誰でも閲覧可（posts と同じ考え方）
drop policy if exists "schedules_public_select" on public.schedules;
create policy "schedules_public_select"
  on public.schedules
  for select
  using (published = true);

-- INSERT / UPDATE / DELETE は RLS では許可しません。
-- すべて下記の SECURITY DEFINER 関数（合言葉検証つき）経由でのみ行います。

-- 3. RPC関数

-- 3-1. 新規作成
create or replace function public.create_schedule(
  key text,
  p_title text,
  p_title_en text default null,
  p_title_kr text default null,
  p_title_tr text default null,
  p_title_de text default null,
  p_rule_label text default null,
  p_tag_color text default 'pink',
  p_image_url text default null,
  p_recurrence_type text default 'weekly',
  p_day_of_week smallint default null,
  p_specific_date date default null,
  p_st_time time default null,
  p_note_text text default null,
  p_note_text_en text default null,
  p_note_text_kr text default null,
  p_note_text_tr text default null,
  p_note_text_de text default null,
  p_important_text text default null,
  p_important_text_en text default null,
  p_important_text_kr text default null,
  p_important_text_tr text default null,
  p_important_text_de text default null,
  p_link_post_id bigint default null,
  p_sort_order integer default 0,
  p_published boolean default true
) returns public.schedules
language plpgsql
security definer
set search_path = public
as $$
declare
  result public.schedules;
begin
  if key <> 'loveSMG' then
    raise exception '合言葉が間違っています';
  end if;

  insert into public.schedules (
    title, title_en, title_kr, title_tr, title_de,
    rule_label, tag_color, image_url,
    recurrence_type, day_of_week, specific_date, st_time,
    note_text, note_text_en, note_text_kr, note_text_tr, note_text_de,
    important_text, important_text_en, important_text_kr, important_text_tr, important_text_de,
    link_post_id, sort_order, published
  ) values (
    p_title, p_title_en, p_title_kr, p_title_tr, p_title_de,
    p_rule_label, p_tag_color, p_image_url,
    p_recurrence_type, p_day_of_week, p_specific_date, p_st_time,
    p_note_text, p_note_text_en, p_note_text_kr, p_note_text_tr, p_note_text_de,
    p_important_text, p_important_text_en, p_important_text_kr, p_important_text_tr, p_important_text_de,
    p_link_post_id, p_sort_order, p_published
  )
  returning * into result;

  return result;
end;
$$;

-- 3-2. 一覧取得（下書き含む、管理画面専用）
create or replace function public.list_all_schedules(key text)
returns setof public.schedules
language plpgsql
security definer
set search_path = public
as $$
begin
  if key <> 'REPLACE_WITH_YOUR_PASSPHRASE' then
    raise exception '合言葉が間違っています';
  end if;

  return query select * from public.schedules order by created_at desc;
end;
$$;

-- 3-3. 更新
create or replace function public.update_schedule(
  schedule_id bigint,
  key text,
  p_title text,
  p_title_en text default null,
  p_title_kr text default null,
  p_title_tr text default null,
  p_title_de text default null,
  p_rule_label text default null,
  p_tag_color text default 'pink',
  p_image_url text default null,
  p_recurrence_type text default 'weekly',
  p_day_of_week smallint default null,
  p_specific_date date default null,
  p_st_time time default null,
  p_note_text text default null,
  p_note_text_en text default null,
  p_note_text_kr text default null,
  p_note_text_tr text default null,
  p_note_text_de text default null,
  p_important_text text default null,
  p_important_text_en text default null,
  p_important_text_kr text default null,
  p_important_text_tr text default null,
  p_important_text_de text default null,
  p_link_post_id bigint default null,
  p_sort_order integer default 0,
  p_published boolean default true
) returns public.schedules
language plpgsql
security definer
set search_path = public
as $$
declare
  result public.schedules;
begin
  if key <> 'REPLACE_WITH_YOUR_PASSPHRASE' then
    raise exception '合言葉が間違っています';
  end if;

  update public.schedules set
    title = p_title,
    title_en = p_title_en,
    title_kr = p_title_kr,
    title_tr = p_title_tr,
    title_de = p_title_de,
    rule_label = p_rule_label,
    tag_color = p_tag_color,
    image_url = p_image_url,
    recurrence_type = p_recurrence_type,
    day_of_week = p_day_of_week,
    specific_date = p_specific_date,
    st_time = p_st_time,
    note_text = p_note_text,
    note_text_en = p_note_text_en,
    note_text_kr = p_note_text_kr,
    note_text_tr = p_note_text_tr,
    note_text_de = p_note_text_de,
    important_text = p_important_text,
    important_text_en = p_important_text_en,
    important_text_kr = p_important_text_kr,
    important_text_tr = p_important_text_tr,
    important_text_de = p_important_text_de,
    link_post_id = p_link_post_id,
    sort_order = p_sort_order,
    published = p_published,
    updated_at = now()
  where id = schedule_id
  returning * into result;

  return result;
end;
$$;

-- 3-4. 削除
create or replace function public.delete_schedule(schedule_id bigint, key text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if key <> 'REPLACE_WITH_YOUR_PASSPHRASE' then
    raise exception '合言葉が間違っています';
  end if;

  delete from public.schedules where id = schedule_id;
end;
$$;

-- 4. 実行権限の付与
grant execute on function public.create_schedule to anon, authenticated;
grant execute on function public.list_all_schedules to anon, authenticated;
grant execute on function public.update_schedule to anon, authenticated;
grant execute on function public.delete_schedule to anon, authenticated;

-- ============================================================
-- 実行後の確認:
--   select * from public.schedules;
-- が空の結果セット（エラーなし）で返ってくればテーブル作成は成功です。
-- ============================================================
